### ISSUE TITLE
Math damage is off?

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#10]
![image](https://github.com/jalensailin/mvrpg/assets/84296981/85a5613f-b6f2-4a97-85b7-59a9ee7ec721)
Not sure what's going on here

Marvel die is 2
Melee Modifier is x1
Melee Bonus is 3

Showing damage as 4 instead of 5

**Comment by fougerec** [comment]
![image](https://github.com/jalensailin/mvrpg/assets/84296981/852d4931-88ad-4fdb-b307-38628099e1f3)
In this one

1st example
Marvel die is a 5
Melee Modifier is 1
Melee Modifier is 1

Showing damage as 7 instead of 6

Example 2
Marvel die is M
Melee Multiplier is 1
Melee modifier is 1

Showing damage as 16 instead of 14.

**Comment by jalensailin** [comment]
This is all quite odd. I will look into it

**Comment by jalensailin** [comment]
This is very strange and I am not yet able to replicate it. Can you give me precise steps to reproduce the issue?

**Comment by fougerec** [comment]
I made a character (using the SHIELD Agent stats) and rolled a Melee attack and then rolled damage.  That was it, nothing fancy.

When I make a new character with everything at default it works.  

Adding some points into things and it still works.  The other three characters though have wonky math on the melee and don't seem to be picking up the Damage Multiplier.  

I'll generate some more characters tomorrow, including completely replicating the ones that aren't adding up right and see what happens.

**Comment by jalensailin** [comment]
were you ever able to confirm this on a fresh actor?

**Comment by fougerec** [comment]
It works fine on a fresh actor.  I've tried replicating different things - adding to the combat tracker, removing them, adding them back, rolling initiative, running a full mock combat etc.  The original two characters I made are still borked but the two new ones work fine.

**Comment by jalensailin** [comment]
if its working as expected on a fresh actor, then I think we are good to close this issue :). i likely changed something in the datamodel that the old actors were relying on
