### ISSUE TITLE
Definitely something going on with the damage calculations

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#11]
![image](https://github.com/jalensailin/mvrpg/assets/84296981/1a8508f7-098a-47a4-9bfb-eb91a79d0780)
Even with Rank 5 and thus minimum damage multiplier of 5 it's only multiplying it by 1.  No errors at all in the console.

**Comment by jalensailin** [comment]
Let's try to keep similar reports in the same Issue. Tracking this in #10
