### ISSUE TITLE
Select multiple Action Costs for Powers (e.g. action or reaction)

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#12]
Certain powers like Anger are listed as a possible action or reaction. Not sure if it will affect the use of the power but it could help to have a choice on the pull down menu that would list both possibilities when creating the powers.
Also the power points that can be spent on a power like Anger are flexible so if you plan to have some automation on that we will need to be able to select the power points spent and not a fix value.

**Comment by jalensailin** [comment]
Thanks for the suggestion! I almost think this should be 2 issues. 
- Select multiple Action Costs for Powers
- Flexible spending of Focus Points

Will change the title of this issue, and open another one accordingly.

**Comment by jalensailin** [comment]
Selecting multiple powers costs should be addressed in the latest update. Closing the issue for now. Let me know if you find any trouble with it and I can reopen the issue as necessary
