### ISSUE TITLE
Error when starting combat showing in chat

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#16]
Here is the print screen or the error in the consol. I used the latest version and all I did was start a combat. You see the error in the console but also in the names of the characters in the chat window.
![image](https://github.com/jalensailin/mvrpg/assets/53952256/cbeb88ca-fc98-45ca-8c16-32a0a5b7809d)

**Comment by jalensailin** [comment]
I'll look into the source of the incorrect strings. Likely changed some translation strings and forgot to update it in certain places. Luckily, the error in the console is from base foundry and has nothing to do with this system :).

**Comment by jalensailin** [comment]
this should be addressed in most recent updates! let me know if the issue persists
