### ISSUE TITLE
Issue in non-combat caluclations

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#19]
I just did an AE on spiderman for Might. So added the +1 on non combat Melee checks in the AE tab. Then rolled a non combat Melee check and if I'm not wrong it should have been 18 with the +1 but it's showing 17 in the chat card.
![image](https://github.com/jalensailin/mvrpg/assets/53952256/6911c117-c898-4c18-bcea-a1610112830c)

**Comment by jalensailin** [comment]
I think this rolled and calculated correctly. Your melee value is 5, and the non-combat value is 6. You rolled a 2, 3 and 6, which added together is 11. 11 + 6 = 17, as shown.

**Comment by RGK13** [comment]
There is an AE of +1 that fid not add I think.

**Comment by jalensailin** [comment]
if there is, i am not seeing it in the screen shot. The base melee value is 5, you have an AE that adds 1 to non combat checks for melee. The melee non-combat section correctly reads as 6 (5+1). Then the roll correctly adds the modifier of 6 (which includes a +1) for non-combat rolls to the total of the roll. Let me know if i'm missing something 😄

**Comment by jalensailin** [comment]
Closing this. Can always open it back up again if necessary
