### ISSUE TITLE
Indicate fantastic success in initiative tracker

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#22]
On initiative rolls, when the participants roll a Fantasctic success they get to participate in a pre Initiative Bonus round. It would be nice to work that in the Combat tracker. Maybe something like a highlighted token or a star on the ones that got the Fantastic success. Also to be able to automatically skip the ones that do not have the Fantastic success for the first round and then start the standard initiative. Also if you could add the hold option in the combat tracker for when the character wants to hold their action (just like the SWADE system) would be very helpful. If the character decides to hold you click the option in the tracker and it pushes the token to the next place and so forth until the character decides to take his action.

**Comment by jalensailin** [comment]
This should be addressed in the latest update. I added a glow effect and a tooltip to the combatants that rolled fantastic success in initiative. **Note**, to see the changes, you will have to update manually by uninstalling and reinstalling from the link in CONTRIBUTING.md

**Comment by jalensailin** [comment]
Oh, and I will open a separate issue for the "Hold" action
