### ISSUE TITLE
Choose which ability defense to roll against and/or set DC

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#25]
I was simulating a combat and noticed that it would be really helpful if on the combat card we get when we use a power (example Dazzle) When I select a target and then make my attack with the power that I could select against witch defense stat I'm fighting. In the case of Dazzle it would be against Vigilance defense of the target. That way we could apply the damage automatically in the chat.

**Comment by jalensailin** [comment]
From user @fougerec in issue #21:

> Detecting the appropriate defense so automating if it was a success or not. Even a field where a DC could be inputted for a non-combat roll would be nice.

**Comment by jalensailin** [comment]
This should be addressed in the most recent update. You *should* be able to update from within foundry but if it doesnt seem to be working, always just uninstall and reinstall
