### ISSUE TITLE
Problem when getting TN from target

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#34]
Look at the screen shot. In this case Doctor Octopus was trying to crush spider-man and normally it should be a Melee check against his melee defense so 19 would be the target but he gave it a success at 14. 
![image](https://github.com/jalensailin/mvrpg/assets/53952256/28633634-1d85-4793-bc39-7ccad475a382)

**Comment by jalensailin** [comment]
I never intended for targeting to have functionality with the latest update.

Also, please double check that there isn't already an open issue for something. The issue just before this one is a duplicate; closing because of that. Thank you!
