### ISSUE TITLE
Label for Action: None showing property name

### ISSUE THREAD

**Issue by Penumbra113** [jalensailin/mvrpg#35]
![image](https://github.com/jalensailin/mvrpg/assets/65138533/257f2959-9253-4736-8f15-fe09b5880ebe)

When choosing the None action for a Power, the property name is being shown on the Powers page rather than "None".

**Comment by jalensailin** [comment]
Thank you for raising the issue :). That should actually be fixed in the dev version, and you made me realize i missed a place where a similar thing was happening, which is also fixed in the dev version now. closing the issue in light of that :)
