### ISSUE TITLE
Rolling from character sheet

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#4]
The buttons to roll are too small and not easily visible. I suggest you make them bigger and if you can make them into a dice icon even better! The players will always look for a dice icon to roll from my experience.

**Comment by jalensailin** [comment]
I can make them larger but don't think theres enough room for a dice icon. i do suggest you take a look at other systems. it is fairly standard practice to have the name of the attribute also be the button that you roll from, and most don't also have a dice icon. Even if at first the players are confused, it should be pretty easy to remember after

**Comment by jalensailin** [comment]
this should be fixed with latest update :)
