### ISSUE TITLE
Fonts not loading on startu[

### ISSUE THREAD

**Issue by reubentaylor** [jalensailin/mvrpg#41]
![image](https://github.com/jalensailin/mvrpg/assets/13823912/2ade1b1c-ec6c-416f-9404-863fe24520d0)
Console is showing a failure to load font family "Amiri" and Font Family "Bruno Ace" on startup
Found version 11 Build 315

**Comment by jalensailin** [comment]
i appreciate the heads up for this, but this is a warning that derives from Foundry and does not have to do with this system (thankfully). Closing
