### ISSUE TITLE
Options for combat roll confirmation

### ISSUE THREAD

**Issue by NinjaPirateBob** [jalensailin/mvrpg#46]
When confirming a combat roll it would be nice to have just a basic input for focus being spent and extra damage to add in the calculation. The focus cost doesn't have to be automated yet but having that query show on the chat card is an easy way to remember to deduct the correct amount. 

Also, there are a lot of powers that add extra damage based on variable focus spent, and inputting how much extra damage should be factored into the calculation would be very useful.

**Comment by WildBillLives** [comment]
I very much second this request - it would make the math a lot easier for some of more 'numbers-challenged' players :-)

Thanks!

**Comment by jalensailin** [comment]
Hi there, apologies for the late response. I am tracking this issue in #15 , so I will close this in favor of that, but I will copy/paste your comment so nothing gets lost. Thank you for your input!
