### ISSUE TITLE
Error in Console in combat

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#5]
Hi, this error popped when starting a combat. Not sure what it is but wanted to let you know in case it's important. Check your discord for the image since I was not able to paste it on this post...Sorry.

**Comment by jalensailin** [comment]
![image](https://github.com/jalensailin/mvrpg/assets/72114365/f8dfe61a-d48a-4e21-8f68-e8140cb6e7d0)

**Comment by jalensailin** [comment]
turns out this is a foundry bug. I tested it in the cyberpunk red system and the 5e system, and it happens in both of them. closing this issue :)
