### ISSUE TITLE
List of attributes for Active Effects

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#6]
As someone with no programming knowledge, a list of attributes for Active Effects would be great when adding items.  For example - if I add the Accuracy Power which increases Agility for non-attack checks and gives +1 to Agility Damage I'm not sure what Attribute keys I need to reference.

**Comment by jalensailin** [comment]
The latest update should address this. As seen in the pictures, I have created a drop-down menu with predetermined options to select for active effects. If you would like to input a custom key, you can do so by changing the input type to text via the toggle button. Let me know what you think or if you encounter any bug. If you do, please open a new issue about the new bug specifically. Thank you!

![image](https://github.com/jalensailin/mvrpg/assets/72114365/4776c6e9-10c9-4c4d-ab50-555111dc2750)
