### ISSUE TITLE
Stacking Edge/Trouble

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#9]
By the rules (page 15) Edge and Trouble can stack and cancel each other out.  It appears as though there's currently just a simple check box for having one or the other and once you've used the reroll there's no option to roll again.

**Comment by jalensailin** [comment]
I'm not sure what you mean here. Edges and Troubles stack/cancel-out, and the math is already done for you. So, if you roll with 3 Edges and 2 Troubles, you will be able to reroll dice with a single Edge. When you click the checkbox, then you can simply adjust the number of edges/troubles up as necessary. Let me know if I misunderstand :).

![image](https://github.com/jalensailin/mvrpg/assets/72114365/b481557f-a7a8-4be6-8ed4-43d51f0b5a9c)

**Comment by fougerec** [comment]
Ah it wasn't clear that you can toggle on Edge/Trouble and then edit the number.  It appeared as those it was just a binary one or off toggle.

Something to bear in mind for eventual system notes perhaps.

**Comment by jalensailin** [comment]
I'll keep it in mind! Thanks
